#if !canImport(ObjectiveC)
import XCTest

extension DateFormatterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DateFormatterTests = [
        ("testDateFromNginxTimeLocal", testDateFromNginxTimeLocal),
        ("testDateToNginxTimeLocal", testDateToNginxTimeLocal),
    ]
}

extension LTSVDecoderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LTSVDecoderTests = [
        ("testLTSVDecodeBoolCustomStrategy", testLTSVDecodeBoolCustomStrategy),
        ("testLTSVDecodeBoolDefaultStrategy", testLTSVDecodeBoolDefaultStrategy),
        ("testLTSVDecodeDateCustomStrategy", testLTSVDecodeDateCustomStrategy),
        ("testLTSVDecodeDateDefferedDateStrategy", testLTSVDecodeDateDefferedDateStrategy),
        ("testLTSVDecodeDateGivenDateFormatterStrategy", testLTSVDecodeDateGivenDateFormatterStrategy),
        ("testLTSVDecodeDateISO8601Strategy", testLTSVDecodeDateISO8601Strategy),
        ("testLTSVDecodeDateMilliSecondsSince1970Strategy", testLTSVDecodeDateMilliSecondsSince1970Strategy),
        ("testLTSVDecodeDateNginxTimeLocalStrategy", testLTSVDecodeDateNginxTimeLocalStrategy),
        ("testLTSVDecodeDateSecondsSince1970Strategy", testLTSVDecodeDateSecondsSince1970Strategy),
        ("testLTSVDecodeEnum", testLTSVDecodeEnum),
        ("testLTSVDecodeRows", testLTSVDecodeRows),
        ("testLTSVDecodeRowsSupoortIntFamily", testLTSVDecodeRowsSupoortIntFamily),
        ("testLTSVDecodeRowsTheEmptyValueFieldAsNil", testLTSVDecodeRowsTheEmptyValueFieldAsNil),
        ("testLTSVDecodeSingleRow", testLTSVDecodeSingleRow),
    ]
}

extension LTSVEncoderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LTSVEncoderTests = [
        ("testLTSVEncodeBoolCustomStrategy", testLTSVEncodeBoolCustomStrategy),
        ("testLTSVEncodeBoolDefaultStrategy", testLTSVEncodeBoolDefaultStrategy),
        ("testLTSVEncodeDateCustomStrategy", testLTSVEncodeDateCustomStrategy),
        ("testLTSVEncodeDateDefferedDateStrategy", testLTSVEncodeDateDefferedDateStrategy),
        ("testLTSVEncodeDateGivenDateFormatterStrategy", testLTSVEncodeDateGivenDateFormatterStrategy),
        ("testLTSVEncodeDateISO8601Strategy", testLTSVEncodeDateISO8601Strategy),
        ("testLTSVEncodeDateMilliSecondsSince1970Strategy", testLTSVEncodeDateMilliSecondsSince1970Strategy),
        ("testLTSVEncodeDateNginxTimeLocalStrategy", testLTSVEncodeDateNginxTimeLocalStrategy),
        ("testLTSVEncodeDateSecondsSince1970Strategy", testLTSVEncodeDateSecondsSince1970Strategy),
        ("testLTSVEncodeRows", testLTSVEncodeRows),
        ("testLTSVEncodeRowsSupoortIntFamily", testLTSVEncodeRowsSupoortIntFamily),
        ("testLTSVEncodeRowsTheEmptyValueFieldAsNil", testLTSVEncodeRowsTheEmptyValueFieldAsNil),
        ("testLTSVEncodeSingleRow", testLTSVEncodeSingleRow),
    ]
}

extension LTSVTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LTSVTests = [
        ("testLTSVParse", testLTSVParse),
        ("testLTSVParseTheEmptyValueFieldAsNil", testLTSVParseTheEmptyValueFieldAsNil),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DateFormatterTests.__allTests__DateFormatterTests),
        testCase(LTSVDecoderTests.__allTests__LTSVDecoderTests),
        testCase(LTSVEncoderTests.__allTests__LTSVEncoderTests),
        testCase(LTSVTests.__allTests__LTSVTests),
    ]
}
#endif
