#if !canImport(ObjectiveC)
import XCTest

extension DateFormatterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DateFormatterTests = [
        ("testDateFromNginxTimeLocal", testDateFromNginxTimeLocal),
        ("testDateToNginxTimeLocal", testDateToNginxTimeLocal),
    ]
}

extension LTSVBidirectionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LTSVBidirectionTests = [
        ("testLTSVBidirectionalBoolCustomStrategy", testLTSVBidirectionalBoolCustomStrategy),
        ("testLTSVBidirectionalBoolDefaultStrategy", testLTSVBidirectionalBoolDefaultStrategy),
        ("testLTSVBidirectionalDateCustomStrategy", testLTSVBidirectionalDateCustomStrategy),
        ("testLTSVBidirectionalDateDefferedDateStrategy", testLTSVBidirectionalDateDefferedDateStrategy),
        ("testLTSVBidirectionalDateGivenDateFormatterStrategy", testLTSVBidirectionalDateGivenDateFormatterStrategy),
        ("testLTSVBidirectionalDateISO8601Strategy", testLTSVBidirectionalDateISO8601Strategy),
        ("testLTSVBidirectionalDateMilliSecondsSince1970Strategy", testLTSVBidirectionalDateMilliSecondsSince1970Strategy),
        ("testLTSVBidirectionalDateNginxTimeLocalStrategy", testLTSVBidirectionalDateNginxTimeLocalStrategy),
        ("testLTSVBidirectionalDateSecondsSince1970Strategy", testLTSVBidirectionalDateSecondsSince1970Strategy),
        ("testLTSVBidirectionalEnum", testLTSVBidirectionalEnum),
        ("testLTSVBidirectionalRows", testLTSVBidirectionalRows),
        ("testLTSVBidirectionalRowsSupoortFloatingPointFamily", testLTSVBidirectionalRowsSupoortFloatingPointFamily),
        ("testLTSVBidirectionalRowsSupoortIntFamily", testLTSVBidirectionalRowsSupoortIntFamily),
        ("testLTSVBidirectionalRowsTheEmptyValueFieldAsNil", testLTSVBidirectionalRowsTheEmptyValueFieldAsNil),
        ("testLTSVBidirectionalSingleRow", testLTSVBidirectionalSingleRow),
        ("testLTSVBidirectionalStringBasedEnum", testLTSVBidirectionalStringBasedEnum),
    ]
}

extension LTSVDecoderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LTSVDecoderTests = [
        ("testLTSVDecodeBoolCustomStrategy", testLTSVDecodeBoolCustomStrategy),
        ("testLTSVDecodeBoolDefaultStrategy", testLTSVDecodeBoolDefaultStrategy),
        ("testLTSVDecodeDateCustomStrategy", testLTSVDecodeDateCustomStrategy),
        ("testLTSVDecodeDateDefferedDateStrategy", testLTSVDecodeDateDefferedDateStrategy),
        ("testLTSVDecodeDateGivenDateFormatterStrategy", testLTSVDecodeDateGivenDateFormatterStrategy),
        ("testLTSVDecodeDateISO8601Strategy", testLTSVDecodeDateISO8601Strategy),
        ("testLTSVDecodeDateMilliSecondsSince1970Strategy", testLTSVDecodeDateMilliSecondsSince1970Strategy),
        ("testLTSVDecodeDateNginxTimeLocalStrategy", testLTSVDecodeDateNginxTimeLocalStrategy),
        ("testLTSVDecodeDateSecondsSince1970Strategy", testLTSVDecodeDateSecondsSince1970Strategy),
        ("testLTSVDecodeDoubleBasedEnum", testLTSVDecodeDoubleBasedEnum),
        ("testLTSVDecodeEnum", testLTSVDecodeEnum),
        ("testLTSVDecodeFloat32BasedEnum", testLTSVDecodeFloat32BasedEnum),
        ("testLTSVDecodeFloat64BasedEnum", testLTSVDecodeFloat64BasedEnum),
        ("testLTSVDecodeFloatBasedEnum", testLTSVDecodeFloatBasedEnum),
        ("testLTSVDecodeRows", testLTSVDecodeRows),
        ("testLTSVDecodeRowsSupoortFloatingPointFamily", testLTSVDecodeRowsSupoortFloatingPointFamily),
        ("testLTSVDecodeRowsSupoortIntFamily", testLTSVDecodeRowsSupoortIntFamily),
        ("testLTSVDecodeRowsTheEmptyValueFieldAsNil", testLTSVDecodeRowsTheEmptyValueFieldAsNil),
        ("testLTSVDecodeSingleRow", testLTSVDecodeSingleRow),
        ("testLTSVDecodeStringBasedEnum", testLTSVDecodeStringBasedEnum),
    ]
}

extension LTSVEncoderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LTSVEncoderTests = [
        ("testLTSVEncodeBoolCustomStrategy", testLTSVEncodeBoolCustomStrategy),
        ("testLTSVEncodeBoolDefaultStrategy", testLTSVEncodeBoolDefaultStrategy),
        ("testLTSVEncodeDateCustomStrategy", testLTSVEncodeDateCustomStrategy),
        ("testLTSVEncodeDateDefferedDateStrategy", testLTSVEncodeDateDefferedDateStrategy),
        ("testLTSVEncodeDateGivenDateFormatterStrategy", testLTSVEncodeDateGivenDateFormatterStrategy),
        ("testLTSVEncodeDateISO8601Strategy", testLTSVEncodeDateISO8601Strategy),
        ("testLTSVEncodeDateMilliSecondsSince1970Strategy", testLTSVEncodeDateMilliSecondsSince1970Strategy),
        ("testLTSVEncodeDateNginxTimeLocalStrategy", testLTSVEncodeDateNginxTimeLocalStrategy),
        ("testLTSVEncodeDateSecondsSince1970Strategy", testLTSVEncodeDateSecondsSince1970Strategy),
        ("testLTSVEncodeDoubleBasedEnum", testLTSVEncodeDoubleBasedEnum),
        ("testLTSVEncodeEnum", testLTSVEncodeEnum),
        ("testLTSVEncodeFloat32BasedEnum", testLTSVEncodeFloat32BasedEnum),
        ("testLTSVEncodeFloat64BasedEnum", testLTSVEncodeFloat64BasedEnum),
        ("testLTSVEncodeFloatBasedEnum", testLTSVEncodeFloatBasedEnum),
        ("testLTSVEncodeRows", testLTSVEncodeRows),
        ("testLTSVEncodeRowsSupoortFloatingPointFamily", testLTSVEncodeRowsSupoortFloatingPointFamily),
        ("testLTSVEncodeRowsSupoortIntFamily", testLTSVEncodeRowsSupoortIntFamily),
        ("testLTSVEncodeRowsTheEmptyValueFieldAsNil", testLTSVEncodeRowsTheEmptyValueFieldAsNil),
        ("testLTSVEncodeSingleRow", testLTSVEncodeSingleRow),
        ("testLTSVEncodeStringBasedEnum", testLTSVEncodeStringBasedEnum),
    ]
}

extension LTSVTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LTSVTests = [
        ("testLTSVParse", testLTSVParse),
        ("testLTSVParseTheEmptyValueFieldAsNil", testLTSVParseTheEmptyValueFieldAsNil),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DateFormatterTests.__allTests__DateFormatterTests),
        testCase(LTSVBidirectionTests.__allTests__LTSVBidirectionTests),
        testCase(LTSVDecoderTests.__allTests__LTSVDecoderTests),
        testCase(LTSVEncoderTests.__allTests__LTSVEncoderTests),
        testCase(LTSVTests.__allTests__LTSVTests),
    ]
}
#endif
